security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                use_referer: true
            two_factor:
                auth_form_path: 2fa_login           # Path or route name of the two-factor form
                check_path: 2fa_login_check         # Path or route name of the two-factor code check
                post_only: true                     # If the check_path should accept the code only as a POST request
                default_target_path: app_accueil    # Where to redirect by default after successful authentication
                auth_code_parameter_name: _auth_code  # Name of the parameter for the two-factor authentication code
                                                      # (supports symfony/property-access notation for nested values)

                # Some two-factor providers need to be "prepared", usually a code is generated and sent to the user. Per
                # default, this happens when the two-factor form is shown. But you may want to execute preparation
                # earlier in the user's journey.
                prepare_on_login: true # If the two-factor provider should be prepared right after login
                prepare_on_access_denied: true      # The the two-factor provider should be prepared when the user has to
                                                    # to complete two-factor authentication to view a page. This would
                                                    # prepare right before redirecting to the two-factor form.

                enable_csrf: true                   # If CSRF protection should be enabled on the two-factor auth form
                csrf_parameter: _csrf_token         # The default CSRF parameter name
                                                    # (supports symfony/property-access notation for nested values)
                csrf_token_id: two_factor           # The default CSRF token id, for generating the token value, it is
                                                    # advised to use a different id per firewall
                csrf_header: ~                      # Name of the header field, in which a CSRF token may be passed.
                                                    # Default null, so headers are ignored per default.

                # The id of the service used to generate the CSRF tokens. Per default the one provided by Symfony
                # is used. You can configure a different one, if you need to use a custom CSRF token manager.
                csrf_token_manager: security.csrf.token_manager

                # If you have multiple user providers registered, Symfony's security extension requires you to configure
                # a user provider. You're forced to configure this node, although it doesn't have any effect on the
                # TwoFactorBundle. So set this to any of your user providers, it doesn't matter which one.
                provider: app_user_provider

            logout:
                path: app_logout
                # where to redirect after logout
                target: app_login

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Le premier access control qui correspond est appliqué
    access_control:

        # This makes the logout route accessible during two-factor authentication. Allows the user to
        # cancel two-factor authentication, if they need to.
        - { path: ^/logout, role: PUBLIC_ACCESS }
        
        # This ensures that the form can only be accessed when two-factor authentication is in progress.
        - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }

        #  Un utilisateur anonyme a uniquement accès à la page de connexion (route /login)
        # correspond à /login/*
        - { path: '^/login', roles: PUBLIC_ACCESS }

        #  Un administrateur a accès à la gestion des catégories
        # correspond à /categorie/* sauf si la règle précédente s'applique
        - { path: '^/categorie/admin', roles: ROLE_ADMIN }

        #  Un administrateur a accès à la gestion des catégories
        # correspond à /user/* sauf si la règle précédente s'applique
        - { path: '^/user', roles: ROLE_ADMIN }

        #  Un utilisateur a accès à tout sauf la gestion des catégories
        # correspond à /* sauf si la règle précédente s'applique
        - { path: '^/*', roles: [ROLE_ADMIN, ROLE_USER] }


when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
