2fa_login:
# route pour le formulaire d'authentification à double facteur
    path: /2fa
    defaults:
        _controller: "scheb_two_factor.form_controller::form"

2fa_login_check:
# route pour la vérification du code d'authentification double facteur
    path: /2fa_check
